### PR TITLE
fixed compile errors to build sway-borders using latest versions of wlr (0.17.0-dev) and sway (1.9-dev)

### PR DESCRIPTION
**Pull request by danielerognini**
included wlr_output_damage.h; used wlr_output_damage_create to convert the wlr_output in the sway_output struct into a wlr_output_damage that will be used by the wlr_output_damage_add function

### CODE REVIEW

**Comment by lindeMAX** [comment]
Hi,
i tried this but it's still producing some errors.
[Here](https://gist.github.com/lindeMAX/037457f6227e771573b800f26be792ae) you can see the log.
Greets

**Comment by lindeMAX** [comment]
It seems to be related to changes made in [wlroots 0.17.0](https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3527)

**Comment by fluix-dev** [comment]
Superseded by https://github.com/fluix-dev/sway-borders/commit/c9cbaf60307e35773785d84a3c28314d1e01208e and https://github.com/fluix-dev/sway-borders/commit/a849fa5f900643a98cc80d813bd929552bce1f3d. It looks like that damage call wasn't really necessary anyways.

**Comment by fluix-dev** [comment]
> It looks like that damage call wasn't really necessary anyways.

And it looks like that isn't quite true. Titlebar borders seem to stick around when unfocusing.

**Pull request closed without merging**
