### PR TITLE
Fix #47, add more rigorous border image verification

### LINKED ISSUE #47: Login loop
Currently for those who dont use a login manager and run sway from tty using autologin, any error in config ( ie. a typo in image file name ) is making sway endlessly loop from tty. Cant even access other tty as you are switched back to sway tty immediately. 
currently only solution is to access the config file using bootable iso and correct the config.
Is is possible to just ignore the shader if the file dont exist ?

### PR DESCRIPTION
**Pull request by ghost**
Checks that the user can read the image, not just that the image exists. Also verifies that a surface can be created, to prevent for example invalid images from causing wlroots to crash due to image width < 1.

### CODE REVIEW

**Comment by Stardust8502** [comment]
bump. @fluix-dev thoughts, suggestions, or concerns?

**Comment by fluix-dev** [comment]
Hey, just been a bit busy. Is there a way to get a more understandable error for different cairo errors instead of a generic "invalid image" log?

**Comment by Stardust8502** [comment]
Yeah, give me a day or so and I'll rewrite it to be more descriptive. I'm thinking `Internal cairo error`, `File not found`, `Unable to read image`, and `Image is not a PNG`.

**Comment by fluix-dev** [comment]
Awesome, although perhaps cairo itself has a sterror function.

**Comment by Stardust8502** [comment]
> sterror function

something like [cairo_status_to_string()](https://cairographics.org/manual/cairo-Error-handling.html#cairo-status-to-string)?

**Comment by fluix-dev** [comment]
> something like [cairo_status_to_string()](https://cairographics.org/manual/cairo-Error-handling.html#cairo-status-to-string)?

Try it; looks about right.

**Comment by Stardust8502** [comment]
Sorry for leaving this untouched for a while. I'm hoping for some free time tomorrow to wrap this up.

**Pull request closed without merging**
